### ISSUE TITLE
JS error after the binary starts

### ISSUE THREAD

**Issue by bansp** [rmraya/Swordfish#11]
Running the most recent binary

Swordfish	5.0.2 Build: 20240303_1649
OpenXLIFF	3.18.0 Build: 20240224_1553
XMLJava	1.7.0 Build: 20240210_0953
Java	21.0.2 Vendor: Eclipse Adoptium
Electron	29.1.0

under

Operating System: Kubuntu 23.04
KDE Plasma Version: 5.27.4
KDE Frameworks Version: 5.104.0
Qt Version: 5.15.8
Kernel Version: 6.2.0-39-generic (64-bit)
Graphics Platform: X11

Right after I run swordfish, the main window opens, the info pop-up shows, and that's followed by the error msg below.

![Screenshot_20240315_014604](https://github.com/rmraya/Swordfish/assets/312137/e501a159-6789-4d8b-9b3c-d061cab9ebc3)

I've been able to install a translation memory, but when I define a project and I'm forced to add file (whether I use the simple or the complex dialog, whether plain text or .odt as the input file, whether I select the memory or not), swordfish hangs with the information "Creating Project" and a spinning cursor.

Full output below.

```
$ Mar 15, 2024 1:50:15 AM com.maxprograms.swordfish.CheckURL checkURL
INFO: ready

(Swordfish:43780): Gtk-WARNING **: 01:50:15.963: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(Swordfish:43780): Gtk-WARNING **: 01:50:15.963: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name

(Swordfish:43780): Gtk-WARNING **: 01:50:16.106: Theme parsing error: gtk.css:1649:16: '-gtk-icon-size' is not a valid property name

(Swordfish:43780): Gtk-WARNING **: 01:50:16.106: Theme parsing error: gtk.css:1652:16: '-gtk-icon-size' is not a valid property name
[43856:0315/015016.219553:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.219726:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.219898:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.220000:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.220154:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.220264:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.220396:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.220465:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.220551:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.220599:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.220681:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.220724:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.220805:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.220848:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.220937:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.220971:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.221045:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.221081:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.221154:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.221187:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.221261:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.221294:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.221367:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.221401:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.221474:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.221517:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.221591:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.221626:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.221700:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.221733:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.221825:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.221866:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.221943:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.221986:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.222061:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.222094:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.222167:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.222201:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.222273:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.222306:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.222380:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.222414:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.222488:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.222521:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.222594:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.222627:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.222702:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.222735:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.222809:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.222842:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.222915:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.222947:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.223020:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.223052:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.223125:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.223159:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.223232:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.223267:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.223340:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.223382:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.223477:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.223513:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.223620:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.223671:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.223772:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.223866:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.224016:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.224077:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.224189:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.224252:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.224365:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.224425:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.224529:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.224586:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.224698:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.224757:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.224868:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.224922:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
[43856:0315/015016.225024:ERROR:gbm_wrapper.cc(76)] Failed to get fd for plane.: No such file or directory (2)
[43856:0315/015016.225072:ERROR:gbm_wrapper.cc(259)] Failed to export buffer to dma_buf: No such file or directory (2)
stderr: Mar 15, 2024 1:50:16 AM com.maxprograms.swordfish.ProjectsHandler handle
SEVERE: Error processing project /projects/list
org.json.JSONException: JSONArray[0] is not a JSONObject (class java.lang.String : Compars-PL).
        at json/org.json.JSONArray.wrongValueFormatException(JSONArray.java:1708)
        at json/org.json.JSONArray.getJSONObject(JSONArray.java:481)
        at swordfish/com.maxprograms.swordfish.ProjectsHandler.sortProjects(Unknown Source)
        at swordfish/com.maxprograms.swordfish.ProjectsHandler.loadProjectsList(Unknown Source)
        at swordfish/com.maxprograms.swordfish.ProjectsHandler.handle(Unknown Source)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

```

Thanks.

**Comment by rmraya** [comment]
There is no intention to support every Linux distribution and Windows Manager.

The program is only tested and supported on OpenSUSE with GNOME. Problems on other Linux versions will not be addressed.

**Comment by bansp** [comment]
Ah, thanks.
