### ISSUE TITLE
Project creation error

### ISSUE THREAD

**Issue by BaronCzerny** [rmraya/Swordfish#12]
When trying to create a new project a get the following Java error message in the console, and the project creation dialogue stays on forever without the project being created:

stderr: May 07, 2024 12:50:49 PM com.maxprograms.swordfish.ProjectsHandler handle
GRAVE: Error processing project /projects/create
org.json.JSONException: JSONArray[0] is not a JSONObject (class java.lang.String : C-E4-849051-sz400).
        at json/org.json.JSONArray.wrongValueFormatException(JSONArray.java:1708)
        at json/org.json.JSONArray.getJSONObject(JSONArray.java:481)
        at swordfish/com.maxprograms.swordfish.ProjectsHandler.sortProjects(Unknown Source)
        at swordfish/com.maxprograms.swordfish.ProjectsHandler.loadProjectsList(Unknown Source)
        at swordfish/com.maxprograms.swordfish.ProjectsHandler.handle(Unknown Source)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
        at jdk.httpserver/sun.net.httpserver.AuthFilter.doFilter(AuthFilter.java:82)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:101)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange$LinkHandler.handle(ServerImpl.java:871)
        at jdk.httpserver/com.sun.net.httpserver.Filter$Chain.doFilter(Filter.java:98)
        at jdk.httpserver/sun.net.httpserver.ServerImpl$Exchange.run(ServerImpl.java:847)
        at java.base/java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1144)
        at java.base/java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:642)
        at java.base/java.lang.Thread.run(Thread.java:1583)

**Comment by rmraya** [comment]
The issue cannot be reproduced if you don't provide the files you are using and indicate exactly how you have built the code.  Copying a stack trace is not enough.
Download the official build and check if you can create a project with it.
